#on:
#  push:
#    tags:
#      - "v*"
on:
  push:
    branches: [ master ]

jobs:
  binding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          ANDROID_HOME=~/.android/sdk
          ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          make binding_android
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output

