on:
  push:
    tags:
      - "v*"

jobs:
  binding:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: make binding_darwin
      - name: Compress
        run: tar -czvf darwin_librsa_bridge.tar.gz output/binding/darwin
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: darwin_librsa_bridge.tar.gz
          tag: ${{ github.ref }}
          overwrite: true