on:
  push:
    tags:
      - "v*"

jobs:
  binding:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: make binding_darwin
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output