#on:
#  push:
#    tags:
#      - "v*"

on:
  push:
    branches: [ master ]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build
        run: |
          export ANDROID_HOME=~/.android/sdk
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export ANDROID_NDK_TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          make gomobile_android
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build
        run: make gomobile_ios
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
