name: Build GoMobile

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Overwrite
        required: false
  push:
    tags:
      - "v*"

env:
  VERSION: ${{ github.event.inputs.version || (startsWith(github.ref, 'refs/tags/') && github.ref || '') }}

jobs:
  android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - name: Install Android Platform
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-29"
          sdkmanager "build-tools;29.0.2"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build
        run: |
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export ANDROID_NDK_TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          make gomobile_android
      - name: Compress
        run: tar -czvf output.tar.gz -C output/android .
      - if: ${{ env.VERSION!='' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: gomobile_rsa_android_aar_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ env.VERSION }}
          overwrite: true
      - if: ${{ env.VERSION=='' }}
        uses: actions/upload-artifact@v2
        with:
          name: gomobile_rsa_android_aar
          path: output.tar.gz

  ios:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build Framework
        run: make gomobile_ios
      - name: Compress Framework
        run: tar -czvf output.tar.gz -C output/ios .
      - name: Build XCFramework
        run: make gomobile_ios_xcframework
      - name: Compress XCFramework
        run: tar -czvf output_xcframework.tar.gz -C output/ios_xcframework .
      - if: ${{ env.VERSION!='' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: gomobile_rsa_ios_framework_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ env.VERSION }}
          overwrite: true
      - if: ${{ env.VERSION=='' }}
        uses: actions/upload-artifact@v2
        with:
          name: gomobile_rsa_ios_framework
          path: output.tar.gz
      - if: ${{ env.VERSION!='' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: gomobile_rsa_ios_xcframework_$tag.tar.gz
          file: output_xcframework.tar.gz
          tag: ${{ env.VERSION }}
          overwrite: true
      - if: ${{ env.VERSION=='' }}
        uses: actions/upload-artifact@v2
        with:
          name: gomobile_rsa_ios_xcframework
          path: output_xcframework.tar.gz
