name: Build GoMobile

on:
  push:
    tags:
      - "v*"

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - name: Install Android Platform
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-29"
          sdkmanager "build-tools;29.0.2"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build
        run: |
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export ANDROID_NDK_TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          make gomobile_android
      - name: Compress
        run: tar -czvf output.tar.gz -C output/android .
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: gomobile_rsa_android_aar_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  ios:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.13'
          # using this version to support more Architectures in the fat file: Openpgp are: armv7 i386 x86_64 arm64
      - name: Install Gomobile
        run: |
          go get -u golang.org/x/mobile/cmd/gomobile@33b80540585f2b31e503da24d6b2a02de3c53ff5
          gomobile init
      - name: Build
        run: make gomobile_ios
      - name: Compress
        run: tar -czvf output.tar.gz -C output/ios .
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: gomobile_rsa_ios_framework_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
