on:
  push:
    tags:
      - "v*"

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - name: Install Android Platform
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-29"
          sdkmanager "build-tools;29.0.2"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build
        run: |
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export ANDROID_NDK_TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          make gomobile_android
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r android_aar.zip output/android
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android_aar.zip
          tag: ${{ github.ref }}
          overwrite: true

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install Gomobile
        run: make gomobile
      - name: Build
        run: make gomobile_ios
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ios_framework.zip output/ios
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ios_framework.zip
          tag: ${{ github.ref }}
          overwrite: true
