on:
  push:
    tags:
      - "v*"

jobs:
  binding:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: make binding_ios
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ios_librsa_bridge.zip output/binding/ios
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ios_librsa_bridge.zip
          tag: ${{ github.ref }}
          overwrite: true