name: Build iOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Overwrite
        required: false
  push:
    tags:
      - "v*"
  pull_request:

env:
  VERSION: ${{ github.event.inputs.version || (startsWith(github.ref, 'refs/tags/') && github.ref || '') }}

jobs:
  binding:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.13'
      - name: Build
        run: make binding_ios
      - name: Compress
        run: tar -czvf output.tar.gz -C output/binding/ios .
      - if: ${{ env.VERSION!='' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: librsa_bridge_ios_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ env.VERSION }}
          overwrite: true
      - if: ${{ env.VERSION=='' }}
        uses: actions/upload-artifact@v2
        with:
          name: librsa_bridge_ios
          path: output.tar.gz