on:
  push:
    tags:
      - "v*"

jobs:
  binding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Build
        run: make binding_linux
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r linux_librsa_bridge.zip output/binding/linux
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux_librsa_bridge.zip
          tag: ${{ github.ref }}
          overwrite: true