name: Build Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  binding:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Build
        run: make binding_linux
      - name: Compress
        run: tar -czvf output.tar.gz -C output/binding/linux .
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: librsa_bridge_linux_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: librsa_bridge_linux
          path: output.tar.gz