name: Build Protobuf

on:
  push:
    paths:
      - '**.proto'

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build
        run: |
          export PATH="$PATH":"$FLUTTER_HOME/.pub-cache/bin"
          make proto_dart_deps
          make proto_dart
      - uses: actions/upload-artifact@v2
        with:
          name: proto_dart
          path: output/dart
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          make proto_go_deps
          make proto_go
      - uses: actions/upload-artifact@v2
        with:
          name: proto_go
          path: bridge/model