#on:
#  push:
#    tags:
#      - "v*"
on:
  push:
    branches: [ master ]
jobs:
  binding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Build
        run: make binding_windows
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
